[build]
builder = "nixpacks"

[build.buildCommand]
value = "npm ci && cd frontend && rm -rf node_modules package-lock.json && npm install && npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[env]
NODE_ENV = "production"