[build]
builder = "nixpacks"

[build.buildCommand]
value = "npm ci && cd frontend && rm -rf node_modules package-lock.json && npm install --legacy-peer-deps --force && npm rebuild && npx vite build --config vite.config.railway.js"

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[env]
NODE_ENV = "production"
NPM_CONFIG_LEGACY_PEER_DEPS = "true"
NPM_CONFIG_OPTIONAL = "true"