services:
  - type: web
    name: vibra-ai-backend
    env: node
    plan: free
    buildCommand: npm install && cd backend && npm install
    startCommand: node backend/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /health